# frozen_string_literal: true

source 'https://rubygems.org'
ruby '3.4.5'

gem 'activerecord', '~> 8.0'
gem 'bcrypt', '~> 3.1'
gem 'pg', '~> 1.6'
gem 'puma', '~> 6.6'
gem 'sinatra', '~> 4.1'
gem 'sinatra-activerecord', '~> 2.0'
gem 'sinatra-flash', '~> 0.3.0'

gem 'rack', '~> 3.2'
gem 'rackup', '~> 2.2'
gem 'rake', '~> 13.3'

group 'development' do
  gem 'rerun', '~> 0.14.0'
  gem 'rubocop', '~> 1.79'
end

